### PR TITLE
Fixed sha for alpine image

### PR DESCRIPTION
**Pull request by Craeckie**
I got a `manifest verification failed for digest`, this is the new hash.

### CODE REVIEW

**Comment by calmh** [comment]
@rubenbe why are we doing this pinning, what does it gain us?

**Comment by rubenbe** [comment]
@calmh This ensures that we always get the exact same images as a base. Docker tags are a moving target, so the same tag could change in a non-backwards compatible way. (Although I agree that the chance is pretty low).

@Craeckie can you tell me how to reproduce that issue? I can still perfectly pull the old alpine image:

```
docker pull alpine:3.6@sha256:1072e499f3f655a032e88542330cf75b02e7bdf673278f701d7ba61629ee3ebe
Trying to pull repository docker.io/library/alpine ... 
sha256:1072e499f3f655a032e88542330cf75b02e7bdf673278f701d7ba61629ee3ebe: Pulling from docker.io/library/alpine
```

Unless docker removes old images, a pinned image should not become "unpullable"

**Comment by calmh** [comment]
I think this is overkill. We depend on so little from the base image that any current or future Alpine image should work fine, I vote for removing the version tag and hash.

**Comment by rubenbe** [comment]
Good point that we indeed don't depend on specific features, so agreed.
I'll make the change later today.

**Comment by rubenbe** [comment]
Unpinned Alpine image

**Pull request closed without merging**
