### PR TITLE
add UDP IPv4 discovery protocol port forward on example

### PR DESCRIPTION
**Pull request by naggie**
In theory, this should allow local discoveries between devices for
faster transfers. I've enabled it and it appears to allow a transfer,
but the address shown is not currently local.

https://github.com/joeybaker/docker-syncthing has also suggested this.

Should it work?

Thanks!

### CODE REVIEW

**Comment by calmh** [comment]
I honestly doubt it as we send/receive broadcasts and multicasts, and I doubt any of those are forwarded by the Docker bridge.

(Also, typo in port number)

**Comment by naggie** [comment]
Ok. I'll try to get it working and close the PR if I fail. Perhaps the best way is to use the docker host network instead, if discovery is required.

**Comment by naggie** [comment]
I've updated the readme with some notes about using the `host` network instead. I hope it's useful

**Comment by calmh** [comment]
Thanks!

**Pull request merged**
